### ISSUE TITLE
PC stutters at fixed interval (maybe when animation loops?)

### ISSUE THREAD

**Issue by hersi97** [Artemis-RGB/Artemis#794]
[Artemis log-20230610.log](https://github.com/Artemis-RGB/Artemis/files/11714705/Artemis.log-20230610.log)

Hi!
I have a really simple profile set up with a linear gradient background (scrolling) and a type wave.
On startup there's nothing wrong but after I have my computer running for a couple hours, the whole PC begins to stutter at a fixed interval (about once every 4-5 seconds, about how long it takes to wrap around the gradient animation), sometimes it's a really small stutter, sometimes it's about (what I feel like) 200-300ms long.
If I close and relaunch the whole rgb stack, the stutter are gone once again for a couple of hours.

Windows 11
X670 chipset
Plugins: OpenRGB, Logitech

**Comment by RVillani** [comment]
I have the exact same issue. Do you use OpenRGB with Artemis? I feel like the stuttering began once I started using it.

**Comment by DarthAffe** [comment]
Hi, to investigate this we'd need a [profiling trace](https://wiki.artemis-rgb.com/en/guides/user/plugins/profiling) taken when this happens.

**Comment by RVillani** [comment]
I tried to profile, but even launching Artemis as Administrator, I get this error after clicking `Start` on the CPU tracer.
```
System.InvalidOperationException: dotTrace console profiler has exited unexpectedly. See details below.
*** Standard Error ***
Unable to start profiling. Administrative rights are required to run Timeline profiling.

*** Standard Output ***
dotTrace command-line profiler 2024.1.6 build 777.0.20240812.141914. Copyright (C) 2024 JetBrains s.r.o.
Preparing to profile...

   at JetBrains.Profiler.SelfApi.Impl.ConsoleProfiler.BuildException(String caption)
   at JetBrains.Profiler.SelfApi.Impl.ConsoleProfiler.AwaitResponse(String command, Int32 milliseconds)
   at JetBrains.Profiler.SelfApi.DotTrace.Session.AwaitConnected()
   at JetBrains.Profiler.SelfApi.DotTrace.Attach(Config config)
   at Artemis.Plugins.Profiling.CpuProfiler.StartProfiling(String dirPath) in D:\a\Artemis\Artemis\Artemis.Plugins\src\Other\Artemis.Plugins.Profiling\CpuProfiler.cs:line 45
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Artemis.Plugins.Profiling.ViewModels.ProfilerConfigurationViewModel.ExecuteStartCpuProfiling() in D:\a\Artemis\Artemis\Artemis.Plugins\src\Other\Artemis.Plugins.Profiling\ViewModels\ProfilerConfigurationViewModel.cs:line 100
```

**Comment by DarthAffe** [comment]
ah, i forgot to mention that:
you need to add the commandline parameter `--force-elevation` (https://wiki.artemis-rgb.com/en/startup-arguments) for this.

**Comment by RVillani** [comment]
Ok, thanks! Once I get it stuttering again, I'll try it once more.

And I think that commandline param should be in the profiling guide you sent earlier. I know it's a bit of duplication with the second page, but it could be a link to the main arguments page.

**Comment by RVillani** [comment]
I managed to capture the tracing profiles, both mem and CPU. I also added small video captures of my desktop playing videos and GIFs while the stutters are happening. I think the rotating duck is the one that highlights it better.

I've uploaded it via [WeTransfer](https://we.tl/t-ViBLysiLpj), as suggested.

Cheers!

**Comment by RVillani** [comment]
Some more info. I hope it helps to track it down.

I was just having a really bad instance of the stutter. The cursor was freezing for what seemed like half a second every 2s or so. I launched the UI to trace a profile, and it was gone! It seems whatever causes the stutters, is temporarily fixed by launching the UI. Perhaps some memory leak that gets cleared?

This confirms a suspicion I had while trying to trace it for the first time. I had to leave the Artemis window minimized, while leaving the JetBrains plugin window open, until the stutters started. Otherwise, when I opened Artemis to do it, it would stop stuttering and I couldn't trace it.

**Comment by DarthAffe** [comment]
That's super weird. The traces look fine to me, nothing really standing out. The only thing is that rendering is that ui rendering is causing most of the cpu usage, but that's explained if you say you had the ui open while tracing.
I don't really see why a memory leak would cause stutters as long as you're not completely running out of memory (which you would see in the task manager) (have you already checked for memory usage?)

Which plugins do you have enabled and which brushes/data models are you using?
If you say it feels like it started after using openrgb it could also be related to something in the communication, but that is something we might not be able to see in artemis traces - but I don't know enough about openrgb to judge that.

**Comment by senposage** [comment]
same issues possibly here: I need to quit artemis before doing anything gpu intensive else the scheduler flips out and starts causing weird machine wide lag I suspect its vulkan trying to allocate gpu resources and the gpu is already busy software rendering seems to work slightly better but still not as good as simply shutting artemis down

**Comment by RVillani** [comment]
I think this has been fixed. I've had Artemis running for 3 consecutive days (didn't shut down Windows) and there's been no hitching yet. This is very different from before, where I'd always have to terminate Artemis in less than a day because the hitching would get longer with time. And this is not the first time I've noticed that stability in the last month.

Yesterday, I even risked playing games with Artemis running. It was a terrible experience before, but this time it was smooth, like when I used to terminate it before running any games.

I still have the same hardware and SDKs as before (Corsair mem sticks controlled via SDK on iCue, mobo and GPU lights via OpenRGB server, and Logitech peripherals via their SDK). That's why I'm suspecting whatever was causing it was software and it's been fixed. Be it on Artemis' side, Windows updates, or any of the aforementioned SDKs. I haven't updated OpenRGB since forever, but Logitech and iCue update themselves, so it could be any of those. It's too many variables.

I hope the other ppl that had this issue have noticed the same.

**Comment by RVillani** [comment]
Unfortunately, I celebrated too soon.

After a driver update (NVidia, Game Ready Driver), the stutter came back. Also, yesterday while playing Spider Man 2. It seems @senposage's hunch is correct regarding heavy GPU usage, or specific kinds of GPU activity.
